# -*- coding: utf-8 -*-
"""stox.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BJ3VtBMXBjutuSlQ7V6K62J6bkLRrU35
"""

import pandas as pd
import numpy as np
from datetime import datetime
import matplotlib.pyplot as plt
plt.style.use('ggplot')

#load data

from google.colab import files
uploaded = files.upload()

AAPL= pd.read_csv('data.csv')

#create simple moving average 30 days
SMA30 = pd.DataFrame()
SMA30['Close']= AAPL['Close'].rolling(window=30).mean()
#SMA30
#create simple moving average 100 days
SMA100 = pd.DataFrame()
SMA100['Close'] = AAPL ['Close'].rolling(window=100).mean()
#SMA100

#visualize DATA
plt.figure(figsize=(19.5,5.5))
plt.plot(AAPL['Close'],label = 'AAPL')
plt.plot(SMA30['Close'],label = 'SMA30')
plt.plot(SMA100['Close'],label = 'SMA100')
plt.title('nifty close price history')
plt.xlabel('jun 02 , 2019 -jun. 12,2020')
plt.ylabel('Close Price Rupee(rs)')
plt.legend(loc='upper left')
plt.show()

#create a new frame to store all data
data = pd.DataFrame()
data['AAPL'] = AAPL['Close']
data['SMA30'] = SMA30['Close']
data['SMA100'] = SMA100['Close']

#create a function for buy and sell signal
def buy_sell(data):
  sigpricebuy = []
  sigpricesell = []
  flag = -1
  for i in range(len(data)):
    if data['SMA30'][i] > data['SMA100'][i]:
      if flag != 1:
        sigpricebuy.append(data['AAPL'][i])
        sigpricesell.append(np.nan)
        flag = 1
      else:
        sigpricebuy.append(np.nan)
        sigpricesell.append(np.nan)
    elif data['SMA30'][i] < data['SMA100'][i]:
      if flag != 0:
        sigpricebuy.append(np.nan)
        sigpricesell.append(data['AAPL'][i])
        flag=0
      else:
        sigpricebuy.append(np.nan)
        sigpricesell.append(np.nan)
    else:
      sigpricebuy.append(np.nan)
      sigpricesell.append(np.nan)
    
  return (sigpricebuy,sigpricesell)

#storing buy and sell data into variable
buy_sell = buy_sell(data)
data['Buy_signal_Price'] = buy_sell[0]
data['Sell_signal_Price'] = buy_sell[1]

#visuallize data
plt.figure(figsize=(19.5,5.5))
plt.plot(data['AAPL'],label = 'AAPL', alpha = 3)
plt.plot(data['SMA30'],label = 'SMA30', alpha = 3)
plt.plot(data['SMA100'],label = 'SMA100', alpha = 3)
plt.scatter(data.index , data['Buy_signal_Price'],label = 'Buy',marker='^', color = 'green',)
plt.scatter(data.index , data['Sell_signal_Price'],label = 'Sell',marker='v', color = 'red')
plt.title('nifty close price history buy sell signals')
plt.xlabel('jun 02 , 2019 -jun. 12,2020')
plt.ylabel('Close Price Rupee(rs)')
plt.legend(loc='upper left')
plt.show()

